language: node_js

node_js:
  - 16

sudo: false

os:
  - osx
  - linux

addons:
  apt:
    packages:
      - libsecret-1-dev

services:
  - xvfb

install:
  - yarn install
  - yarn run build-dev

script:
  - yarn run travis-test