language: node_js

node_js:
  - 12

sudo: false

os:
  - osx
  - linux

addons:
  apt:
    packages:
      - libsecret-1-dev

services:
  - xvfb

install:
  - npm install
  - npm run build-dev

script:
  - npm run travis-test