blank_issues_enabled: false
contact_links:
  - name: Textile Language Features on Visual Studio marketplace
    url: https://marketplace.visualstudio.com/items?itemName=GehDoc.vscode-textile-preview
    about: Please rate or give feedback here